# Backtest configs for the 27 "zero-shot" datasets.
# These datasets were not seen by Chronos models during training.
- name: monash_cif_2016
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: monash_car_parts
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: monash_hospital
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: monash_fred_md
  hf_repo: autogluon/chronos_datasets
  offset: -12
  prediction_length: 12
  num_rolls: 1
- name: exchange_rate
  hf_repo: autogluon/chronos_datasets
  offset: -30
  prediction_length: 30
  num_rolls: 1
- name: monash_covid_deaths
  hf_repo: autogluon/chronos_datasets
  offset: -30
  prediction_length: 30
  num_rolls: 1
- name: monash_traffic
  hf_repo: autogluon/chronos_datasets
  offset: -24
  prediction_length: 24
  num_rolls: 1
- name: monash_m3_monthly
  hf_repo: autogluon/chronos_datasets
  offset: -18
  prediction_length: 18
  num_rolls: 1